config/routes.rb
DispatchReq::Application.routes.draw do
  devise_for :users

  resources :profiles
  resources :requests

  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  root to: 'static_pages#home'
end

app/models/center.rb
class Center < ActiveRecord::Base
  attr_accessible :name

  has_many :users
  has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :bill_status, :center_id, :cit_level, :contact_name, :contact_phone, :cust_name, :jde, :notes, :office_down, :parts, :phone, :priority, :time_est

  belongs_to :center
  belongs_to :user

  validates :center_id, :cit_level, :contact_name, :user_id, :cust_name,
            :jde, :notes, :phone, :priority, :time_est, :bill_status, presence: true

  default_scope order: 'requests.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :center_id, :name

  belongs_to :center
  has_many :requests

  VALID_EMAIL_REGEX = /\A[\w+\-.]+(@henryschein.com)$/i
  validates :email, format: VALID_EMAIL_REGEX
  validates :name, :center_id, presence: true

  def confirm!
    send_welcome_email
    super
  end

protected

  def confirmation_required?
    false
  end

private

  def send_welcome_email
    DispatchMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    @requests = @user.requests.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user = current_user
    @request = current_user.requests.build
  end

  def create
    @request = current_user.requests.build(params[:request])
    if @request.save
      flash[:success] = "Dispatch created!"
      redirect_to profile_path(current_user.id)
    else
      render 'requests/new'
    end
  end

  def show
    @request = Request.find(params[:id])
    @user = current_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @user = current_user
      @requests = Request.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::SessionsController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="column">
  <small>
    Images and Logos Copyright of Henry Schein, Inc.
  </small>
  <nav>
    <ul>
      <li><%= link_to 'Home', 'static_pages/home' %></li>
      <li><%= link_to 'Help', 'static_pages/help' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <nav>
          <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li class="welcome">Signed in as <%= link_to current_user.name, profile_path(current_user),
                                                  id: "techname" %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
          <li><%= link_to "Home",   '/static_pages/home' %></li>
          <li><%= link_to "Help",   '/static_pages/help' %></li>
          <li><%= link_to "About",  '/static_pages/about' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>DispatchLink for TechCentral | <%= yield(:title) %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
  <div class="column">
    <body>
		  <%= render 'layouts/header' %>
		  <div class="container column">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
		  </div>
      <section class="container">
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </section>
    </body>
  </div>
</html>

app/views/profiles/edit.html.erb
<% provide(title: "Edit Profile") %>
<h2>Edit Profile</h2>
<div class="span6 offset3">
  <%= form_for(@user) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>

  <%= gravatar_for @user %>
  <%= link_to "Need to change profile image?", "http://gravatar.com/emails" %>
</div>

app/views/profiles/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/profiles/show.html.erb
<% provide(:title, "#{@user.name}'s Profile") %>
<div class="row">
  <aside class="span4">
    <section class"left">
      <h3>
        <%= gravatar_for(@user) %>
        <%= @user.name %>
      </h3>
      <a href="http://gravatar.com/emails">Change gravatar image</a>
    </section>
    <nav class="profilenav span8">
      <ul>
        <li><%= link_to "Create Dispatch", new_request_path, class: "btn" %></li>
        <li><%= link_to "Find Dispatch", '#', class: "btn" %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path, class: "btn" %></li>
      </ul>
    </nav>
  </aside>
  <div class="span8">
    <% if @user.requests.any? %>
      <h2>My Requests</h2>
      <ol>
        <%= render @requests %>
      </ok>
      <%= will_paginate @requests %>
    <% end %>
  </div>
</div>

app/views/profiles/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/requests/_request.html.erb
<li>
  <span class="subject"><%= link_to request.cust_name, request_path(request.id) %></span><br/>
  <span class="timestamp">
    Sent <%= time_ago_in_words(request.created_at) %> ago.
  </span>
</li>

app/views/requests/_requests.html.erb
<li>
  <span class="subject"><%= request.cust_name %></span>
  <span class="timestamp">
    Sent <%= time_ago_in_words(request.created_at) %>ago.
  </span>
</li>

app/views/requests/new.html.erb
<% provide(:title, "Create Dispatch") %>

<div class="row">
  <h3>Dispatch requested by: <%= current_user.name %></h3><br />
  <%= form_for(@request) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <section class="span6 controls">
      <%= f.label :center_id, "Center" %>
      <%= collection_select :request, :center_id, Center.all, :id, :name %>

      <%= f.label :cust_name, "Client Account Name" %>
      <%= f.text_field :cust_name %>

      <%= f.label :phone, "Office Phone" %>
      <%= f.phone_field :phone, placeholder: "Primary phone on account" %>

      <%= f.label :jde, "JDE Number" %>
      <%= f.number_field :jde %>

      <%= f.label :contact_name %>
      <%= f.text_field :contact_name %>

      <%= f.label :contact_phone, "Contact phone" %>
      <%= f.text_field :contact_phone, placeholder: "555-555-5555 ext. 5" %>
    </section>

    <section class="span6 controls secondcolumn">
      <%= f.label :bill_status, "Billing type for service" %>
      <%= f.text_field :bill_status, placeholder: "HTWR, HTRG, HTEM, HTSS, TBD" %>

      <%= f.label :priority %>
      <%= f.text_field :priority, placeholder: "Normal, High, Emergency" %>

      <%= f.label :time_est, "Time requested for service (hours)" %>
      <%= f.number_field :time_est %>

      <%= f.label :cit_level, "CIT Level requested" %>
      <%= f.text_field :cit_level, placeholder: "Specify CIT here, if requested" %>

      <%= f.label :parts, "Additional parts/tools requested" %>
      <%= f.text_field :parts %>

      <div class="form-inline checkbox">
        <%= f.label :office_down, "Yes", value: "true"  %>
        <%= f.radio_button :office_down, true %>
        <%= f.label :office_down, "No", value: "false" %>
        <%= f.radio_button :office_down, false, checked: true %>
        <%= f.label "Does the office need to be down for service?" %>
      </div>
    </section>

    <section class="span12">
      <%= f.label :notes %>
      <%= f.text_area :notes, placeholder: "Concise description of troubleshooting done and further instruction",
                              class: "technotes" %>
    </section>

    <section class="span12 center">
      <%= f.submit "Create dispatch and send email", class: "btn btn-large btn-primary" %>
    </section>
  <% end %>
</div>

app/views/requests/show.html.erb
<h3>Dispatch Request #<%= @request.id %></h3>
<p>Requested by: <%= User.find(@request.user_id).name %></p>
<table class="request-table span6">
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Center:</p>
    </td>
    <td>
      <p><%= Center.find(@request.center_id).name %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Client Account Name:</p>
    </td>
    <td>
      <p><%= @request.cust_name %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Office Phone:</p>
    </td>
    <td>
      <p><%= @request.phone %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>JDE:</p>
    </td>
    <td>
      <p><%= @request.jde %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Contact Name:</p>
    </td>
    <td>
      <p><%= @request.contact_name %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Contact Phone</p>
    </td>
    <td>
      <p><%= @request.contact_phone %></p>
    </td>
  </tr>
</table>
<table class="request-table span6">
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Billing Type:</p>
    </td>
    <td>
      <p><%= @request.bill_status %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Priority:</p>
    </td>
    <td>
      <p><%= @request.priority %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Time Requested:</p>
    </td>
    <td>
      <p><%= @request.time_est %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>CIT Level:</p>
    </td>
    <td>
      <p><%= @request.cit_level %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Additional Parts:</p>
    </td>
    <td>
      <p><%= @request.parts %></p>
    </td>
  </tr>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <p>Down for service?</p>
    </td>
    <td>
      <% if @request.office_down %>
        <p>Yes</p>
      <% else %>
        <p>No</p>
      <% end %>
    </td>
  </tr>
</table>
<section class="span12">
  <p>Notes<br/>
    <%= @request.notes %>
  </p>
</section>

app/views/shared/_request_info.html.erb
<% if Request.count > 0 %>
  <h2>Recent Requests</h2>
    <ol>
      <%= render @requests %>
    </ol>
  <%= will_paginate @requests %>
<% end %>

app/views/shared/_user_info.html.erb
<h3>
  <%= gravatar_for(@user) %>
  <%= @user.name %>
</h3>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="center bg">
  <div class="hsps"></div>
  <h3><br/><br/>
    This application is intended solely for use
    by Team Schein Members to increase visibility
    and communication between TechCentral Remote Support
    and local centers nationwide to provide the highest
    quality and seamless support to our customers.
  </h3>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center bg">
  <div class="hsps"></div>
  <br/><br/><br/><br/><br/>
  <h2>Don't worry. <i>We know.</i> That's why we're here.</h2>
   <p class="center">Click the link below to contact TechCentral Remote Support.</p>
	<h3><%= link_to "Help Me TC!", "http://helpmetc.com" %></h3>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if user_signed_in? %>
<div class="row">
  <aside class="span6">
    <section class"left">
      <%= render 'shared/user_info' %>
    </section>
    <nav class="profilenav span8">
      <ul>
        <li><%= link_to "Create Dispatch", new_request_path, class: "btn btn-primary btn-profile" %></li>
        <li><%= link_to "Find Dispatch", '#', class: "btn btn-primary btn-profile" %></li>
      </ul>
    </nav>
  </aside>
  <div class="span6">
    <%= render 'shared/request_info' %>
  </div>
</div>
<% else %>
<div class="center hero-unit">
  <h1 class="center">Welcome to DispatchLink!</h1>

  <h2>Authorized access only.</h2>

  <%= link_to "Sign up here", new_user_registration_path, class: "btn btn-large btn-primary" %>
</div>
<% end %>